### ISSUE TITLE
Missing semicolon

### ISSUE THREAD

**Issue by voyti** [mrMarshalX/betterQuerySelector#1]
Hello,

I noticed missing semicolon at https://github.com/mrMarshalX/betterQuerySelector/blob/master/betterQuerySelector.js#L2

I realize it is extensively argued within JavaScript community that semicolons may be omitted as long as we realize and stick to the ASI  rules (it's a style that is, among others, used by js standard: https://github.com/feross/standard).

Having said that, I can't help but notice that other lines on your code are in fact using manual semicolon insertions, like this one:
https://github.com/mrMarshalX/betterQuerySelector/blob/master/betterQuerySelector.js#L4
which in result is making the code style inconsistent.

Being a great fan of this project, I would be honored if you took my advice and tried to refactor the code so it is consistent. Regardless, this is a great library that has saved me hours of work and I can't be more impressed or grateful for your work.

**Comment by MrRigby** [comment]
+1 for this

**Comment by mrMarshalX** [comment]
Fixed. Thanks for pointing it out!

Reference [ea82ecf](https://github.com/mrMarshalX/betterQuerySelector/commit/ea82ecf49978805769e525d683d056acf447bc8c)

**Comment by voyti** [comment]
Sweet! Easily best repo on github now. Keep up the good work!

**Comment by MrRigby** [comment]
+1 for this again
